version: "3.9"

services:
  web:
    build: .
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    depends_on:
      - redis
  celery:
    build: .
    command: celery -A test_celery worker --loglevel=INFO
    volumes:
      - .:/usr/src/app
    depends_on:
      - web
      - redis
  redis:
    image: "redis:alpine"   

